services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: kleapi
    ports:
      - "82:82"
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - kleapi-network  # Bu satırın doğru olduğundan emin olun
    environment:
      - LC_ALL=tr_TR.UTF-8
      - LANG=tr_TR.UTF-8

  db:
    image: mysql:latest
    container_name: kleapi-db  
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kleapi-db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: root
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    networks:
      - kleapi-network  

networks:
  kleapi-network:

volumes:
  mysql-data: